// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gestaoturbo.proxies;

public class MaintenanceOrder implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject maintenanceOrderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GestaoTurbo.MaintenanceOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ExecutionDate("ExecutionDate"),
		StartTime("StartTime"),
		EndTime("EndTime"),
		OrderStatus("OrderStatus"),
		MaintenanceOrder_TechnicalEvaluation("GestaoTurbo.MaintenanceOrder_TechnicalEvaluation"),
		MaintenanceOrder_Performer("GestaoTurbo.MaintenanceOrder_Performer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MaintenanceOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MaintenanceOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject maintenanceOrderMendixObject)
	{
		if (maintenanceOrderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, maintenanceOrderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.maintenanceOrderMendixObject = maintenanceOrderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static gestaoturbo.proxies.MaintenanceOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new gestaoturbo.proxies.MaintenanceOrder(context, mendixObject);
	}

	public static gestaoturbo.proxies.MaintenanceOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return gestaoturbo.proxies.MaintenanceOrder.initialize(context, mendixObject);
	}

	public static java.util.List<gestaoturbo.proxies.MaintenanceOrder> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> gestaoturbo.proxies.MaintenanceOrder.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ExecutionDate
	 */
	public final java.util.Date getExecutionDate()
	{
		return getExecutionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExecutionDate
	 */
	public final java.util.Date getExecutionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExecutionDate.toString());
	}

	/**
	 * Set value of ExecutionDate
	 * @param executiondate
	 */
	public final void setExecutionDate(java.util.Date executiondate)
	{
		setExecutionDate(getContext(), executiondate);
	}

	/**
	 * Set value of ExecutionDate
	 * @param context
	 * @param executiondate
	 */
	public final void setExecutionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date executiondate)
	{
		getMendixObject().setValue(context, MemberNames.ExecutionDate.toString(), executiondate);
	}

	/**
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime()
	{
		return getStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartTime.toString());
	}

	/**
	 * Set value of StartTime
	 * @param starttime
	 */
	public final void setStartTime(java.util.Date starttime)
	{
		setStartTime(getContext(), starttime);
	}

	/**
	 * Set value of StartTime
	 * @param context
	 * @param starttime
	 */
	public final void setStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.StartTime.toString(), starttime);
	}

	/**
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime()
	{
		return getEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndTime.toString());
	}

	/**
	 * Set value of EndTime
	 * @param endtime
	 */
	public final void setEndTime(java.util.Date endtime)
	{
		setEndTime(getContext(), endtime);
	}

	/**
	 * Set value of EndTime
	 * @param context
	 * @param endtime
	 */
	public final void setEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.EndTime.toString(), endtime);
	}

	/**
	 * Get value of OrderStatus
	 * @param orderstatus
	 */
	public final gestaoturbo.proxies.OrderStatus getOrderStatus()
	{
		return getOrderStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderStatus
	 */
	public final gestaoturbo.proxies.OrderStatus getOrderStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.OrderStatus.toString());
		if (obj == null) {
			return null;
		}
		return gestaoturbo.proxies.OrderStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of OrderStatus
	 * @param orderstatus
	 */
	public final void setOrderStatus(gestaoturbo.proxies.OrderStatus orderstatus)
	{
		setOrderStatus(getContext(), orderstatus);
	}

	/**
	 * Set value of OrderStatus
	 * @param context
	 * @param orderstatus
	 */
	public final void setOrderStatus(com.mendix.systemwideinterfaces.core.IContext context, gestaoturbo.proxies.OrderStatus orderstatus)
	{
		if (orderstatus != null) {
			getMendixObject().setValue(context, MemberNames.OrderStatus.toString(), orderstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.OrderStatus.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MaintenanceOrder_TechnicalEvaluation
	 */
	public final gestaoturbo.proxies.TechnicalEvaluation getMaintenanceOrder_TechnicalEvaluation() throws com.mendix.core.CoreException
	{
		return getMaintenanceOrder_TechnicalEvaluation(getContext());
	}

	/**
	 * @param context
	 * @return value of MaintenanceOrder_TechnicalEvaluation
	 * @throws com.mendix.core.CoreException
	 */
	public final gestaoturbo.proxies.TechnicalEvaluation getMaintenanceOrder_TechnicalEvaluation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		gestaoturbo.proxies.TechnicalEvaluation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MaintenanceOrder_TechnicalEvaluation.toString());
		if (identifier != null) {
			result = gestaoturbo.proxies.TechnicalEvaluation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MaintenanceOrder_TechnicalEvaluation
	 * @param maintenanceorder_technicalevaluation
	 */
	public final void setMaintenanceOrder_TechnicalEvaluation(gestaoturbo.proxies.TechnicalEvaluation maintenanceorder_technicalevaluation)
	{
		setMaintenanceOrder_TechnicalEvaluation(getContext(), maintenanceorder_technicalevaluation);
	}

	/**
	 * Set value of MaintenanceOrder_TechnicalEvaluation
	 * @param context
	 * @param maintenanceorder_technicalevaluation
	 */
	public final void setMaintenanceOrder_TechnicalEvaluation(com.mendix.systemwideinterfaces.core.IContext context, gestaoturbo.proxies.TechnicalEvaluation maintenanceorder_technicalevaluation)
	{
		if (maintenanceorder_technicalevaluation == null) {
			getMendixObject().setValue(context, MemberNames.MaintenanceOrder_TechnicalEvaluation.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MaintenanceOrder_TechnicalEvaluation.toString(), maintenanceorder_technicalevaluation.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MaintenanceOrder_Performer
	 */
	public final administration.proxies.Account getMaintenanceOrder_Performer() throws com.mendix.core.CoreException
	{
		return getMaintenanceOrder_Performer(getContext());
	}

	/**
	 * @param context
	 * @return value of MaintenanceOrder_Performer
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getMaintenanceOrder_Performer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MaintenanceOrder_Performer.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MaintenanceOrder_Performer
	 * @param maintenanceorder_performer
	 */
	public final void setMaintenanceOrder_Performer(administration.proxies.Account maintenanceorder_performer)
	{
		setMaintenanceOrder_Performer(getContext(), maintenanceorder_performer);
	}

	/**
	 * Set value of MaintenanceOrder_Performer
	 * @param context
	 * @param maintenanceorder_performer
	 */
	public final void setMaintenanceOrder_Performer(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account maintenanceorder_performer)
	{
		if (maintenanceorder_performer == null) {
			getMendixObject().setValue(context, MemberNames.MaintenanceOrder_Performer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MaintenanceOrder_Performer.toString(), maintenanceorder_performer.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return maintenanceOrderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final gestaoturbo.proxies.MaintenanceOrder that = (gestaoturbo.proxies.MaintenanceOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
