// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package formbuilder.proxies;

public class FormNames implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject formNamesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FormBuilder.FormNames";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FormName("FormName"),
		FormId("FormId"),
		Title("Title"),
		Description("Description"),
		ShowDesription("ShowDesription"),
		ExpiryDate("ExpiryDate"),
		ResponsesTaken_Count("ResponsesTaken_Count"),
		AdminDisables_Responses("AdminDisables_Responses"),
		TakeResponses("TakeResponses"),
		FilledResponses_Count("FilledResponses_Count"),
		DeepLinkUrl("DeepLinkUrl"),
		UseDeepLink("UseDeepLink");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FormNames(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FormNames(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject formNamesMendixObject)
	{
		if (formNamesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, formNamesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.formNamesMendixObject = formNamesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static formbuilder.proxies.FormNames initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new formbuilder.proxies.FormNames(context, mendixObject);
	}

	public static formbuilder.proxies.FormNames load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return formbuilder.proxies.FormNames.initialize(context, mendixObject);
	}

	public static java.util.List<formbuilder.proxies.FormNames> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> formbuilder.proxies.FormNames.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of FormName
	 */
	public final java.lang.String getFormName()
	{
		return getFormName(getContext());
	}

	/**
	 * @param context
	 * @return value of FormName
	 */
	public final java.lang.String getFormName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FormName.toString());
	}

	/**
	 * Set value of FormName
	 * @param formname
	 */
	public final void setFormName(java.lang.String formname)
	{
		setFormName(getContext(), formname);
	}

	/**
	 * Set value of FormName
	 * @param context
	 * @param formname
	 */
	public final void setFormName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String formname)
	{
		getMendixObject().setValue(context, MemberNames.FormName.toString(), formname);
	}

	/**
	 * @return value of FormId
	 */
	public final java.lang.Long getFormId()
	{
		return getFormId(getContext());
	}

	/**
	 * @param context
	 * @return value of FormId
	 */
	public final java.lang.Long getFormId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.FormId.toString());
	}

	/**
	 * Set value of FormId
	 * @param formid
	 */
	public final void setFormId(java.lang.Long formid)
	{
		setFormId(getContext(), formid);
	}

	/**
	 * Set value of FormId
	 * @param context
	 * @param formid
	 */
	public final void setFormId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long formid)
	{
		getMendixObject().setValue(context, MemberNames.FormId.toString(), formid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of ShowDesription
	 */
	public final java.lang.Boolean getShowDesription()
	{
		return getShowDesription(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowDesription
	 */
	public final java.lang.Boolean getShowDesription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowDesription.toString());
	}

	/**
	 * Set value of ShowDesription
	 * @param showdesription
	 */
	public final void setShowDesription(java.lang.Boolean showdesription)
	{
		setShowDesription(getContext(), showdesription);
	}

	/**
	 * Set value of ShowDesription
	 * @param context
	 * @param showdesription
	 */
	public final void setShowDesription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showdesription)
	{
		getMendixObject().setValue(context, MemberNames.ShowDesription.toString(), showdesription);
	}

	/**
	 * @return value of ExpiryDate
	 */
	public final java.util.Date getExpiryDate()
	{
		return getExpiryDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpiryDate
	 */
	public final java.util.Date getExpiryDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExpiryDate.toString());
	}

	/**
	 * Set value of ExpiryDate
	 * @param expirydate
	 */
	public final void setExpiryDate(java.util.Date expirydate)
	{
		setExpiryDate(getContext(), expirydate);
	}

	/**
	 * Set value of ExpiryDate
	 * @param context
	 * @param expirydate
	 */
	public final void setExpiryDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expirydate)
	{
		getMendixObject().setValue(context, MemberNames.ExpiryDate.toString(), expirydate);
	}

	/**
	 * @return value of ResponsesTaken_Count
	 */
	public final java.lang.Integer getResponsesTaken_Count()
	{
		return getResponsesTaken_Count(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponsesTaken_Count
	 */
	public final java.lang.Integer getResponsesTaken_Count(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ResponsesTaken_Count.toString());
	}

	/**
	 * Set value of ResponsesTaken_Count
	 * @param responsestaken_count
	 */
	public final void setResponsesTaken_Count(java.lang.Integer responsestaken_count)
	{
		setResponsesTaken_Count(getContext(), responsestaken_count);
	}

	/**
	 * Set value of ResponsesTaken_Count
	 * @param context
	 * @param responsestaken_count
	 */
	public final void setResponsesTaken_Count(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer responsestaken_count)
	{
		getMendixObject().setValue(context, MemberNames.ResponsesTaken_Count.toString(), responsestaken_count);
	}

	/**
	 * @return value of AdminDisables_Responses
	 */
	public final java.lang.Boolean getAdminDisables_Responses()
	{
		return getAdminDisables_Responses(getContext());
	}

	/**
	 * @param context
	 * @return value of AdminDisables_Responses
	 */
	public final java.lang.Boolean getAdminDisables_Responses(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AdminDisables_Responses.toString());
	}

	/**
	 * Set value of AdminDisables_Responses
	 * @param admindisables_responses
	 */
	public final void setAdminDisables_Responses(java.lang.Boolean admindisables_responses)
	{
		setAdminDisables_Responses(getContext(), admindisables_responses);
	}

	/**
	 * Set value of AdminDisables_Responses
	 * @param context
	 * @param admindisables_responses
	 */
	public final void setAdminDisables_Responses(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean admindisables_responses)
	{
		getMendixObject().setValue(context, MemberNames.AdminDisables_Responses.toString(), admindisables_responses);
	}

	/**
	 * @return value of TakeResponses
	 */
	public final java.lang.Boolean getTakeResponses()
	{
		return getTakeResponses(getContext());
	}

	/**
	 * @param context
	 * @return value of TakeResponses
	 */
	public final java.lang.Boolean getTakeResponses(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TakeResponses.toString());
	}

	/**
	 * Set value of TakeResponses
	 * @param takeresponses
	 */
	public final void setTakeResponses(java.lang.Boolean takeresponses)
	{
		setTakeResponses(getContext(), takeresponses);
	}

	/**
	 * Set value of TakeResponses
	 * @param context
	 * @param takeresponses
	 */
	public final void setTakeResponses(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean takeresponses)
	{
		getMendixObject().setValue(context, MemberNames.TakeResponses.toString(), takeresponses);
	}

	/**
	 * @return value of FilledResponses_Count
	 */
	public final java.lang.Integer getFilledResponses_Count()
	{
		return getFilledResponses_Count(getContext());
	}

	/**
	 * @param context
	 * @return value of FilledResponses_Count
	 */
	public final java.lang.Integer getFilledResponses_Count(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FilledResponses_Count.toString());
	}

	/**
	 * Set value of FilledResponses_Count
	 * @param filledresponses_count
	 */
	public final void setFilledResponses_Count(java.lang.Integer filledresponses_count)
	{
		setFilledResponses_Count(getContext(), filledresponses_count);
	}

	/**
	 * Set value of FilledResponses_Count
	 * @param context
	 * @param filledresponses_count
	 */
	public final void setFilledResponses_Count(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer filledresponses_count)
	{
		getMendixObject().setValue(context, MemberNames.FilledResponses_Count.toString(), filledresponses_count);
	}

	/**
	 * @return value of DeepLinkUrl
	 */
	public final java.lang.String getDeepLinkUrl()
	{
		return getDeepLinkUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of DeepLinkUrl
	 */
	public final java.lang.String getDeepLinkUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeepLinkUrl.toString());
	}

	/**
	 * Set value of DeepLinkUrl
	 * @param deeplinkurl
	 */
	public final void setDeepLinkUrl(java.lang.String deeplinkurl)
	{
		setDeepLinkUrl(getContext(), deeplinkurl);
	}

	/**
	 * Set value of DeepLinkUrl
	 * @param context
	 * @param deeplinkurl
	 */
	public final void setDeepLinkUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deeplinkurl)
	{
		getMendixObject().setValue(context, MemberNames.DeepLinkUrl.toString(), deeplinkurl);
	}

	/**
	 * @return value of UseDeepLink
	 */
	public final java.lang.Boolean getUseDeepLink()
	{
		return getUseDeepLink(getContext());
	}

	/**
	 * @param context
	 * @return value of UseDeepLink
	 */
	public final java.lang.Boolean getUseDeepLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseDeepLink.toString());
	}

	/**
	 * Set value of UseDeepLink
	 * @param usedeeplink
	 */
	public final void setUseDeepLink(java.lang.Boolean usedeeplink)
	{
		setUseDeepLink(getContext(), usedeeplink);
	}

	/**
	 * Set value of UseDeepLink
	 * @param context
	 * @param usedeeplink
	 */
	public final void setUseDeepLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usedeeplink)
	{
		getMendixObject().setValue(context, MemberNames.UseDeepLink.toString(), usedeeplink);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return formNamesMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final formbuilder.proxies.FormNames that = (formbuilder.proxies.FormNames) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
