// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package formbuilder.proxies;

public class FormField implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject formFieldMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FormBuilder.FormField";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Label("Label"),
		IsMandatory("IsMandatory"),
		FieldType("FieldType"),
		SortOrder("SortOrder"),
		UpperValue("UpperValue"),
		LowerValue("LowerValue"),
		DateTime("DateTime"),
		MinDate("MinDate"),
		MaxDate("MaxDate"),
		FormField_FormNames("FormBuilder.FormField_FormNames");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FormField(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FormField(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject formFieldMendixObject)
	{
		if (formFieldMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, formFieldMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.formFieldMendixObject = formFieldMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static formbuilder.proxies.FormField initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new formbuilder.proxies.FormField(context, mendixObject);
	}

	public static formbuilder.proxies.FormField load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return formbuilder.proxies.FormField.initialize(context, mendixObject);
	}

	public static java.util.List<formbuilder.proxies.FormField> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> formbuilder.proxies.FormField.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of IsMandatory
	 */
	public final java.lang.Boolean getIsMandatory()
	{
		return getIsMandatory(getContext());
	}

	/**
	 * @param context
	 * @return value of IsMandatory
	 */
	public final java.lang.Boolean getIsMandatory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsMandatory.toString());
	}

	/**
	 * Set value of IsMandatory
	 * @param ismandatory
	 */
	public final void setIsMandatory(java.lang.Boolean ismandatory)
	{
		setIsMandatory(getContext(), ismandatory);
	}

	/**
	 * Set value of IsMandatory
	 * @param context
	 * @param ismandatory
	 */
	public final void setIsMandatory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ismandatory)
	{
		getMendixObject().setValue(context, MemberNames.IsMandatory.toString(), ismandatory);
	}

	/**
	 * Get value of FieldType
	 * @param fieldtype
	 */
	public final formbuilder.proxies.Enum_FieldType getFieldType()
	{
		return getFieldType(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldType
	 */
	public final formbuilder.proxies.Enum_FieldType getFieldType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FieldType.toString());
		if (obj == null) {
			return null;
		}
		return formbuilder.proxies.Enum_FieldType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FieldType
	 * @param fieldtype
	 */
	public final void setFieldType(formbuilder.proxies.Enum_FieldType fieldtype)
	{
		setFieldType(getContext(), fieldtype);
	}

	/**
	 * Set value of FieldType
	 * @param context
	 * @param fieldtype
	 */
	public final void setFieldType(com.mendix.systemwideinterfaces.core.IContext context, formbuilder.proxies.Enum_FieldType fieldtype)
	{
		if (fieldtype != null) {
			getMendixObject().setValue(context, MemberNames.FieldType.toString(), fieldtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.FieldType.toString(), null);
		}
	}

	/**
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder()
	{
		return getSortOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortOrder.toString());
	}

	/**
	 * Set value of SortOrder
	 * @param sortorder
	 */
	public final void setSortOrder(java.lang.Integer sortorder)
	{
		setSortOrder(getContext(), sortorder);
	}

	/**
	 * Set value of SortOrder
	 * @param context
	 * @param sortorder
	 */
	public final void setSortOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortorder)
	{
		getMendixObject().setValue(context, MemberNames.SortOrder.toString(), sortorder);
	}

	/**
	 * @return value of UpperValue
	 */
	public final java.lang.Integer getUpperValue()
	{
		return getUpperValue(getContext());
	}

	/**
	 * @param context
	 * @return value of UpperValue
	 */
	public final java.lang.Integer getUpperValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.UpperValue.toString());
	}

	/**
	 * Set value of UpperValue
	 * @param uppervalue
	 */
	public final void setUpperValue(java.lang.Integer uppervalue)
	{
		setUpperValue(getContext(), uppervalue);
	}

	/**
	 * Set value of UpperValue
	 * @param context
	 * @param uppervalue
	 */
	public final void setUpperValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer uppervalue)
	{
		getMendixObject().setValue(context, MemberNames.UpperValue.toString(), uppervalue);
	}

	/**
	 * @return value of LowerValue
	 */
	public final java.lang.Integer getLowerValue()
	{
		return getLowerValue(getContext());
	}

	/**
	 * @param context
	 * @return value of LowerValue
	 */
	public final java.lang.Integer getLowerValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.LowerValue.toString());
	}

	/**
	 * Set value of LowerValue
	 * @param lowervalue
	 */
	public final void setLowerValue(java.lang.Integer lowervalue)
	{
		setLowerValue(getContext(), lowervalue);
	}

	/**
	 * Set value of LowerValue
	 * @param context
	 * @param lowervalue
	 */
	public final void setLowerValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer lowervalue)
	{
		getMendixObject().setValue(context, MemberNames.LowerValue.toString(), lowervalue);
	}

	/**
	 * @return value of DateTime
	 */
	public final java.lang.Boolean getDateTime()
	{
		return getDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTime
	 */
	public final java.lang.Boolean getDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DateTime.toString());
	}

	/**
	 * Set value of DateTime
	 * @param datetime
	 */
	public final void setDateTime(java.lang.Boolean datetime)
	{
		setDateTime(getContext(), datetime);
	}

	/**
	 * Set value of DateTime
	 * @param context
	 * @param datetime
	 */
	public final void setDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean datetime)
	{
		getMendixObject().setValue(context, MemberNames.DateTime.toString(), datetime);
	}

	/**
	 * @return value of MinDate
	 */
	public final java.util.Date getMinDate()
	{
		return getMinDate(getContext());
	}

	/**
	 * @param context
	 * @return value of MinDate
	 */
	public final java.util.Date getMinDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MinDate.toString());
	}

	/**
	 * Set value of MinDate
	 * @param mindate
	 */
	public final void setMinDate(java.util.Date mindate)
	{
		setMinDate(getContext(), mindate);
	}

	/**
	 * Set value of MinDate
	 * @param context
	 * @param mindate
	 */
	public final void setMinDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date mindate)
	{
		getMendixObject().setValue(context, MemberNames.MinDate.toString(), mindate);
	}

	/**
	 * @return value of MaxDate
	 */
	public final java.util.Date getMaxDate()
	{
		return getMaxDate(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxDate
	 */
	public final java.util.Date getMaxDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MaxDate.toString());
	}

	/**
	 * Set value of MaxDate
	 * @param maxdate
	 */
	public final void setMaxDate(java.util.Date maxdate)
	{
		setMaxDate(getContext(), maxdate);
	}

	/**
	 * Set value of MaxDate
	 * @param context
	 * @param maxdate
	 */
	public final void setMaxDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date maxdate)
	{
		getMendixObject().setValue(context, MemberNames.MaxDate.toString(), maxdate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FormField_FormNames
	 */
	public final formbuilder.proxies.FormNames getFormField_FormNames() throws com.mendix.core.CoreException
	{
		return getFormField_FormNames(getContext());
	}

	/**
	 * @param context
	 * @return value of FormField_FormNames
	 * @throws com.mendix.core.CoreException
	 */
	public final formbuilder.proxies.FormNames getFormField_FormNames(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		formbuilder.proxies.FormNames result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FormField_FormNames.toString());
		if (identifier != null) {
			result = formbuilder.proxies.FormNames.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FormField_FormNames
	 * @param formfield_formnames
	 */
	public final void setFormField_FormNames(formbuilder.proxies.FormNames formfield_formnames)
	{
		setFormField_FormNames(getContext(), formfield_formnames);
	}

	/**
	 * Set value of FormField_FormNames
	 * @param context
	 * @param formfield_formnames
	 */
	public final void setFormField_FormNames(com.mendix.systemwideinterfaces.core.IContext context, formbuilder.proxies.FormNames formfield_formnames)
	{
		if (formfield_formnames == null) {
			getMendixObject().setValue(context, MemberNames.FormField_FormNames.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FormField_FormNames.toString(), formfield_formnames.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return formFieldMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final formbuilder.proxies.FormField that = (formbuilder.proxies.FormField) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
