// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package formbuilder.proxies;

public class FormResponse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject formResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FormBuilder.FormResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Username("Username"),
		Submitted("Submitted"),
		FormId("FormId"),
		FormName("FormName"),
		Description("Description"),
		ShowDescription("ShowDescription");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FormResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FormResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject formResponseMendixObject)
	{
		if (formResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, formResponseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.formResponseMendixObject = formResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static formbuilder.proxies.FormResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new formbuilder.proxies.FormResponse(context, mendixObject);
	}

	public static formbuilder.proxies.FormResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return formbuilder.proxies.FormResponse.initialize(context, mendixObject);
	}

	public static java.util.List<formbuilder.proxies.FormResponse> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> formbuilder.proxies.FormResponse.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Submitted
	 */
	public final java.lang.Boolean getSubmitted()
	{
		return getSubmitted(getContext());
	}

	/**
	 * @param context
	 * @return value of Submitted
	 */
	public final java.lang.Boolean getSubmitted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Submitted.toString());
	}

	/**
	 * Set value of Submitted
	 * @param submitted
	 */
	public final void setSubmitted(java.lang.Boolean submitted)
	{
		setSubmitted(getContext(), submitted);
	}

	/**
	 * Set value of Submitted
	 * @param context
	 * @param submitted
	 */
	public final void setSubmitted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean submitted)
	{
		getMendixObject().setValue(context, MemberNames.Submitted.toString(), submitted);
	}

	/**
	 * @return value of FormId
	 */
	public final java.lang.Integer getFormId()
	{
		return getFormId(getContext());
	}

	/**
	 * @param context
	 * @return value of FormId
	 */
	public final java.lang.Integer getFormId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FormId.toString());
	}

	/**
	 * Set value of FormId
	 * @param formid
	 */
	public final void setFormId(java.lang.Integer formid)
	{
		setFormId(getContext(), formid);
	}

	/**
	 * Set value of FormId
	 * @param context
	 * @param formid
	 */
	public final void setFormId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer formid)
	{
		getMendixObject().setValue(context, MemberNames.FormId.toString(), formid);
	}

	/**
	 * @return value of FormName
	 */
	public final java.lang.String getFormName()
	{
		return getFormName(getContext());
	}

	/**
	 * @param context
	 * @return value of FormName
	 */
	public final java.lang.String getFormName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FormName.toString());
	}

	/**
	 * Set value of FormName
	 * @param formname
	 */
	public final void setFormName(java.lang.String formname)
	{
		setFormName(getContext(), formname);
	}

	/**
	 * Set value of FormName
	 * @param context
	 * @param formname
	 */
	public final void setFormName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String formname)
	{
		getMendixObject().setValue(context, MemberNames.FormName.toString(), formname);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of ShowDescription
	 */
	public final java.lang.Boolean getShowDescription()
	{
		return getShowDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowDescription
	 */
	public final java.lang.Boolean getShowDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowDescription.toString());
	}

	/**
	 * Set value of ShowDescription
	 * @param showdescription
	 */
	public final void setShowDescription(java.lang.Boolean showdescription)
	{
		setShowDescription(getContext(), showdescription);
	}

	/**
	 * Set value of ShowDescription
	 * @param context
	 * @param showdescription
	 */
	public final void setShowDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showdescription)
	{
		getMendixObject().setValue(context, MemberNames.ShowDescription.toString(), showdescription);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return formResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final formbuilder.proxies.FormResponse that = (formbuilder.proxies.FormResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
