// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package formbuilder.proxies;

public class FormField_Response implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject formField_ResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FormBuilder.FormField_Response";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Label("Label"),
		IsMandatory("IsMandatory"),
		FieldType("FieldType"),
		SortOrder("SortOrder"),
		Text_Response("Text_Response"),
		DateValue("DateValue"),
		Integer_Response("Integer_Response"),
		UpperValue("UpperValue"),
		LowerValue("LowerValue"),
		SwitchValue("SwitchValue"),
		DateTime("DateTime"),
		MinDate("MinDate"),
		MaxDate("MaxDate"),
		EndDate("EndDate"),
		FormField_Response_Options("FormBuilder.FormField_Response_Options"),
		FormField_Response_FormResponse("FormBuilder.FormField_Response_FormResponse"),
		FormField_Response_Options_2("FormBuilder.FormField_Response_Options_2");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FormField_Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FormField_Response(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject formField_ResponseMendixObject)
	{
		if (formField_ResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, formField_ResponseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.formField_ResponseMendixObject = formField_ResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static formbuilder.proxies.FormField_Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new formbuilder.proxies.FormField_Response(context, mendixObject);
	}

	public static formbuilder.proxies.FormField_Response load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return formbuilder.proxies.FormField_Response.initialize(context, mendixObject);
	}

	public static java.util.List<formbuilder.proxies.FormField_Response> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> formbuilder.proxies.FormField_Response.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of IsMandatory
	 */
	public final java.lang.Boolean getIsMandatory()
	{
		return getIsMandatory(getContext());
	}

	/**
	 * @param context
	 * @return value of IsMandatory
	 */
	public final java.lang.Boolean getIsMandatory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsMandatory.toString());
	}

	/**
	 * Set value of IsMandatory
	 * @param ismandatory
	 */
	public final void setIsMandatory(java.lang.Boolean ismandatory)
	{
		setIsMandatory(getContext(), ismandatory);
	}

	/**
	 * Set value of IsMandatory
	 * @param context
	 * @param ismandatory
	 */
	public final void setIsMandatory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ismandatory)
	{
		getMendixObject().setValue(context, MemberNames.IsMandatory.toString(), ismandatory);
	}

	/**
	 * Get value of FieldType
	 * @param fieldtype
	 */
	public final formbuilder.proxies.Enum_FieldType getFieldType()
	{
		return getFieldType(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldType
	 */
	public final formbuilder.proxies.Enum_FieldType getFieldType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FieldType.toString());
		if (obj == null) {
			return null;
		}
		return formbuilder.proxies.Enum_FieldType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FieldType
	 * @param fieldtype
	 */
	public final void setFieldType(formbuilder.proxies.Enum_FieldType fieldtype)
	{
		setFieldType(getContext(), fieldtype);
	}

	/**
	 * Set value of FieldType
	 * @param context
	 * @param fieldtype
	 */
	public final void setFieldType(com.mendix.systemwideinterfaces.core.IContext context, formbuilder.proxies.Enum_FieldType fieldtype)
	{
		if (fieldtype != null) {
			getMendixObject().setValue(context, MemberNames.FieldType.toString(), fieldtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.FieldType.toString(), null);
		}
	}

	/**
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder()
	{
		return getSortOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortOrder.toString());
	}

	/**
	 * Set value of SortOrder
	 * @param sortorder
	 */
	public final void setSortOrder(java.lang.Integer sortorder)
	{
		setSortOrder(getContext(), sortorder);
	}

	/**
	 * Set value of SortOrder
	 * @param context
	 * @param sortorder
	 */
	public final void setSortOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortorder)
	{
		getMendixObject().setValue(context, MemberNames.SortOrder.toString(), sortorder);
	}

	/**
	 * @return value of Text_Response
	 */
	public final java.lang.String getText_Response()
	{
		return getText_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of Text_Response
	 */
	public final java.lang.String getText_Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text_Response.toString());
	}

	/**
	 * Set value of Text_Response
	 * @param text_response
	 */
	public final void setText_Response(java.lang.String text_response)
	{
		setText_Response(getContext(), text_response);
	}

	/**
	 * Set value of Text_Response
	 * @param context
	 * @param text_response
	 */
	public final void setText_Response(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text_response)
	{
		getMendixObject().setValue(context, MemberNames.Text_Response.toString(), text_response);
	}

	/**
	 * @return value of DateValue
	 */
	public final java.util.Date getDateValue()
	{
		return getDateValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DateValue
	 */
	public final java.util.Date getDateValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateValue.toString());
	}

	/**
	 * Set value of DateValue
	 * @param datevalue
	 */
	public final void setDateValue(java.util.Date datevalue)
	{
		setDateValue(getContext(), datevalue);
	}

	/**
	 * Set value of DateValue
	 * @param context
	 * @param datevalue
	 */
	public final void setDateValue(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datevalue)
	{
		getMendixObject().setValue(context, MemberNames.DateValue.toString(), datevalue);
	}

	/**
	 * @return value of Integer_Response
	 */
	public final java.lang.Integer getInteger_Response()
	{
		return getInteger_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of Integer_Response
	 */
	public final java.lang.Integer getInteger_Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Integer_Response.toString());
	}

	/**
	 * Set value of Integer_Response
	 * @param integer_response
	 */
	public final void setInteger_Response(java.lang.Integer integer_response)
	{
		setInteger_Response(getContext(), integer_response);
	}

	/**
	 * Set value of Integer_Response
	 * @param context
	 * @param integer_response
	 */
	public final void setInteger_Response(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer integer_response)
	{
		getMendixObject().setValue(context, MemberNames.Integer_Response.toString(), integer_response);
	}

	/**
	 * @return value of UpperValue
	 */
	public final java.lang.Integer getUpperValue()
	{
		return getUpperValue(getContext());
	}

	/**
	 * @param context
	 * @return value of UpperValue
	 */
	public final java.lang.Integer getUpperValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.UpperValue.toString());
	}

	/**
	 * Set value of UpperValue
	 * @param uppervalue
	 */
	public final void setUpperValue(java.lang.Integer uppervalue)
	{
		setUpperValue(getContext(), uppervalue);
	}

	/**
	 * Set value of UpperValue
	 * @param context
	 * @param uppervalue
	 */
	public final void setUpperValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer uppervalue)
	{
		getMendixObject().setValue(context, MemberNames.UpperValue.toString(), uppervalue);
	}

	/**
	 * @return value of LowerValue
	 */
	public final java.lang.Integer getLowerValue()
	{
		return getLowerValue(getContext());
	}

	/**
	 * @param context
	 * @return value of LowerValue
	 */
	public final java.lang.Integer getLowerValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.LowerValue.toString());
	}

	/**
	 * Set value of LowerValue
	 * @param lowervalue
	 */
	public final void setLowerValue(java.lang.Integer lowervalue)
	{
		setLowerValue(getContext(), lowervalue);
	}

	/**
	 * Set value of LowerValue
	 * @param context
	 * @param lowervalue
	 */
	public final void setLowerValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer lowervalue)
	{
		getMendixObject().setValue(context, MemberNames.LowerValue.toString(), lowervalue);
	}

	/**
	 * @return value of SwitchValue
	 */
	public final java.lang.Boolean getSwitchValue()
	{
		return getSwitchValue(getContext());
	}

	/**
	 * @param context
	 * @return value of SwitchValue
	 */
	public final java.lang.Boolean getSwitchValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SwitchValue.toString());
	}

	/**
	 * Set value of SwitchValue
	 * @param switchvalue
	 */
	public final void setSwitchValue(java.lang.Boolean switchvalue)
	{
		setSwitchValue(getContext(), switchvalue);
	}

	/**
	 * Set value of SwitchValue
	 * @param context
	 * @param switchvalue
	 */
	public final void setSwitchValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean switchvalue)
	{
		getMendixObject().setValue(context, MemberNames.SwitchValue.toString(), switchvalue);
	}

	/**
	 * @return value of DateTime
	 */
	public final java.lang.Boolean getDateTime()
	{
		return getDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTime
	 */
	public final java.lang.Boolean getDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DateTime.toString());
	}

	/**
	 * Set value of DateTime
	 * @param datetime
	 */
	public final void setDateTime(java.lang.Boolean datetime)
	{
		setDateTime(getContext(), datetime);
	}

	/**
	 * Set value of DateTime
	 * @param context
	 * @param datetime
	 */
	public final void setDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean datetime)
	{
		getMendixObject().setValue(context, MemberNames.DateTime.toString(), datetime);
	}

	/**
	 * @return value of MinDate
	 */
	public final java.util.Date getMinDate()
	{
		return getMinDate(getContext());
	}

	/**
	 * @param context
	 * @return value of MinDate
	 */
	public final java.util.Date getMinDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MinDate.toString());
	}

	/**
	 * Set value of MinDate
	 * @param mindate
	 */
	public final void setMinDate(java.util.Date mindate)
	{
		setMinDate(getContext(), mindate);
	}

	/**
	 * Set value of MinDate
	 * @param context
	 * @param mindate
	 */
	public final void setMinDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date mindate)
	{
		getMendixObject().setValue(context, MemberNames.MinDate.toString(), mindate);
	}

	/**
	 * @return value of MaxDate
	 */
	public final java.util.Date getMaxDate()
	{
		return getMaxDate(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxDate
	 */
	public final java.util.Date getMaxDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MaxDate.toString());
	}

	/**
	 * Set value of MaxDate
	 * @param maxdate
	 */
	public final void setMaxDate(java.util.Date maxdate)
	{
		setMaxDate(getContext(), maxdate);
	}

	/**
	 * Set value of MaxDate
	 * @param context
	 * @param maxdate
	 */
	public final void setMaxDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date maxdate)
	{
		getMendixObject().setValue(context, MemberNames.MaxDate.toString(), maxdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FormField_Response_Options
	 */
	public final formbuilder.proxies.Options getFormField_Response_Options() throws com.mendix.core.CoreException
	{
		return getFormField_Response_Options(getContext());
	}

	/**
	 * @param context
	 * @return value of FormField_Response_Options
	 * @throws com.mendix.core.CoreException
	 */
	public final formbuilder.proxies.Options getFormField_Response_Options(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		formbuilder.proxies.Options result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FormField_Response_Options.toString());
		if (identifier != null) {
			result = formbuilder.proxies.Options.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FormField_Response_Options
	 * @param formfield_response_options
	 */
	public final void setFormField_Response_Options(formbuilder.proxies.Options formfield_response_options)
	{
		setFormField_Response_Options(getContext(), formfield_response_options);
	}

	/**
	 * Set value of FormField_Response_Options
	 * @param context
	 * @param formfield_response_options
	 */
	public final void setFormField_Response_Options(com.mendix.systemwideinterfaces.core.IContext context, formbuilder.proxies.Options formfield_response_options)
	{
		if (formfield_response_options == null) {
			getMendixObject().setValue(context, MemberNames.FormField_Response_Options.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FormField_Response_Options.toString(), formfield_response_options.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FormField_Response_FormResponse
	 */
	public final formbuilder.proxies.FormResponse getFormField_Response_FormResponse() throws com.mendix.core.CoreException
	{
		return getFormField_Response_FormResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of FormField_Response_FormResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final formbuilder.proxies.FormResponse getFormField_Response_FormResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		formbuilder.proxies.FormResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FormField_Response_FormResponse.toString());
		if (identifier != null) {
			result = formbuilder.proxies.FormResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FormField_Response_FormResponse
	 * @param formfield_response_formresponse
	 */
	public final void setFormField_Response_FormResponse(formbuilder.proxies.FormResponse formfield_response_formresponse)
	{
		setFormField_Response_FormResponse(getContext(), formfield_response_formresponse);
	}

	/**
	 * Set value of FormField_Response_FormResponse
	 * @param context
	 * @param formfield_response_formresponse
	 */
	public final void setFormField_Response_FormResponse(com.mendix.systemwideinterfaces.core.IContext context, formbuilder.proxies.FormResponse formfield_response_formresponse)
	{
		if (formfield_response_formresponse == null) {
			getMendixObject().setValue(context, MemberNames.FormField_Response_FormResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FormField_Response_FormResponse.toString(), formfield_response_formresponse.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FormField_Response_Options_2
	 */
	public final java.util.List<formbuilder.proxies.Options> getFormField_Response_Options_2() throws com.mendix.core.CoreException
	{
		return getFormField_Response_Options_2(getContext());
	}

	/**
	 * @param context
	 * @return value of FormField_Response_Options_2
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<formbuilder.proxies.Options> getFormField_Response_Options_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<formbuilder.proxies.Options> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.FormField_Response_Options_2.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(formbuilder.proxies.Options.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of FormField_Response_Options_2
	 * @param formfield_response_options_2
	 */
	public final void setFormField_Response_Options_2(java.util.List<formbuilder.proxies.Options> formfield_response_options_2)
	{
		setFormField_Response_Options_2(getContext(), formfield_response_options_2);
	}

	/**
	 * Set value of FormField_Response_Options_2
	 * @param context
	 * @param formfield_response_options_2
	 */
	public final void setFormField_Response_Options_2(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<formbuilder.proxies.Options> formfield_response_options_2)
	{
		var identifiers = formfield_response_options_2
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.FormField_Response_Options_2.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return formField_ResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final formbuilder.proxies.FormField_Response that = (formbuilder.proxies.FormField_Response) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
