// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package formbuilder.proxies;

public class Options implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject optionsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FormBuilder.Options";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Label("Label"),
		SortOrder("SortOrder"),
		Options_FormField("FormBuilder.Options_FormField"),
		Options_FormField_Response("FormBuilder.Options_FormField_Response");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Options(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Options(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject optionsMendixObject)
	{
		if (optionsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, optionsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.optionsMendixObject = optionsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static formbuilder.proxies.Options initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new formbuilder.proxies.Options(context, mendixObject);
	}

	public static formbuilder.proxies.Options load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return formbuilder.proxies.Options.initialize(context, mendixObject);
	}

	public static java.util.List<formbuilder.proxies.Options> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> formbuilder.proxies.Options.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder()
	{
		return getSortOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortOrder.toString());
	}

	/**
	 * Set value of SortOrder
	 * @param sortorder
	 */
	public final void setSortOrder(java.lang.Integer sortorder)
	{
		setSortOrder(getContext(), sortorder);
	}

	/**
	 * Set value of SortOrder
	 * @param context
	 * @param sortorder
	 */
	public final void setSortOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortorder)
	{
		getMendixObject().setValue(context, MemberNames.SortOrder.toString(), sortorder);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Options_FormField
	 */
	public final formbuilder.proxies.FormField getOptions_FormField() throws com.mendix.core.CoreException
	{
		return getOptions_FormField(getContext());
	}

	/**
	 * @param context
	 * @return value of Options_FormField
	 * @throws com.mendix.core.CoreException
	 */
	public final formbuilder.proxies.FormField getOptions_FormField(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		formbuilder.proxies.FormField result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Options_FormField.toString());
		if (identifier != null) {
			result = formbuilder.proxies.FormField.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Options_FormField
	 * @param options_formfield
	 */
	public final void setOptions_FormField(formbuilder.proxies.FormField options_formfield)
	{
		setOptions_FormField(getContext(), options_formfield);
	}

	/**
	 * Set value of Options_FormField
	 * @param context
	 * @param options_formfield
	 */
	public final void setOptions_FormField(com.mendix.systemwideinterfaces.core.IContext context, formbuilder.proxies.FormField options_formfield)
	{
		if (options_formfield == null) {
			getMendixObject().setValue(context, MemberNames.Options_FormField.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Options_FormField.toString(), options_formfield.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Options_FormField_Response
	 */
	public final formbuilder.proxies.FormField_Response getOptions_FormField_Response() throws com.mendix.core.CoreException
	{
		return getOptions_FormField_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of Options_FormField_Response
	 * @throws com.mendix.core.CoreException
	 */
	public final formbuilder.proxies.FormField_Response getOptions_FormField_Response(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		formbuilder.proxies.FormField_Response result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Options_FormField_Response.toString());
		if (identifier != null) {
			result = formbuilder.proxies.FormField_Response.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Options_FormField_Response
	 * @param options_formfield_response
	 */
	public final void setOptions_FormField_Response(formbuilder.proxies.FormField_Response options_formfield_response)
	{
		setOptions_FormField_Response(getContext(), options_formfield_response);
	}

	/**
	 * Set value of Options_FormField_Response
	 * @param context
	 * @param options_formfield_response
	 */
	public final void setOptions_FormField_Response(com.mendix.systemwideinterfaces.core.IContext context, formbuilder.proxies.FormField_Response options_formfield_response)
	{
		if (options_formfield_response == null) {
			getMendixObject().setValue(context, MemberNames.Options_FormField_Response.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Options_FormField_Response.toString(), options_formfield_response.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return optionsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final formbuilder.proxies.Options that = (formbuilder.proxies.Options) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
