// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gestaoturbo.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the GestaoTurbo module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Budget_RejectBuilder(
		gestaoturbo.proxies.Budget _budget,
		gestaoturbo.proxies.TechnicalEvaluation _technicalEvaluation
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.ACT_Budget_Reject");
		builder = builder.withParam("Budget", _budget);
		builder = builder.withParam("TechnicalEvaluation", _technicalEvaluation);
		return builder;
	}

	public static void aCT_Budget_Reject(
		IContext context,
		gestaoturbo.proxies.Budget _budget,
		gestaoturbo.proxies.TechnicalEvaluation _technicalEvaluation
	)
	{
		aCT_Budget_RejectBuilder(
				_budget,
				_technicalEvaluation
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Budget_ReviewBuilder(
		gestaoturbo.proxies.Budget _budget,
		gestaoturbo.proxies.TechnicalEvaluation _technicalEvaluation
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.ACT_Budget_Review");
		builder = builder.withParam("Budget", _budget);
		builder = builder.withParam("TechnicalEvaluation", _technicalEvaluation);
		return builder;
	}

	public static void aCT_Budget_Review(
		IContext context,
		gestaoturbo.proxies.Budget _budget,
		gestaoturbo.proxies.TechnicalEvaluation _technicalEvaluation
	)
	{
		aCT_Budget_ReviewBuilder(
				_budget,
				_technicalEvaluation
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BudgetActive_EditBuilder(
		gestaoturbo.proxies.TechnicalEvaluation _technicalEvaluation
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.ACT_BudgetActive_Edit");
		builder = builder.withParam("TechnicalEvaluation", _technicalEvaluation);
		return builder;
	}

	public static void aCT_BudgetActive_Edit(
		IContext context,
		gestaoturbo.proxies.TechnicalEvaluation _technicalEvaluation
	)
	{
		aCT_BudgetActive_EditBuilder(
				_technicalEvaluation
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Client_EditBuilder(
		gestaoturbo.proxies.Client _client
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.ACT_Client_Edit");
		builder = builder.withParam("Client", _client);
		return builder;
	}

	public static void aCT_Client_Edit(
		IContext context,
		gestaoturbo.proxies.Client _client
	)
	{
		aCT_Client_EditBuilder(
				_client
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Create_New_ClientBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.ACT_Create_New_Client");
		return builder;
	}

	public static void aCT_Create_New_Client(IContext context)
	{
		aCT_Create_New_ClientBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Generate_BudgetBuilder(
		gestaoturbo.proxies.Budget _budget,
		gestaoturbo.proxies.TechnicalEvaluation _technicalEvaluation
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.ACT_Generate_Budget");
		builder = builder.withParam("Budget", _budget);
		builder = builder.withParam("TechnicalEvaluation", _technicalEvaluation);
		return builder;
	}

	public static void aCT_Generate_Budget(
		IContext context,
		gestaoturbo.proxies.Budget _budget,
		gestaoturbo.proxies.TechnicalEvaluation _technicalEvaluation
	)
	{
		aCT_Generate_BudgetBuilder(
				_budget,
				_technicalEvaluation
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Retrive_MyTechnicalEvaluationsOnGoingBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.ACT_Retrive_MyTechnicalEvaluationsOnGoing");
		return builder;
	}

	public static java.util.List<gestaoturbo.proxies.TechnicalEvaluation> aCT_Retrive_MyTechnicalEvaluationsOnGoing(IContext context)
	{
		Object result = aCT_Retrive_MyTechnicalEvaluationsOnGoingBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> gestaoturbo.proxies.TechnicalEvaluation.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_RetriveCalendarConfigBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.ACT_RetriveCalendarConfig");
		return builder;
	}

	public static gestaoturbo.proxies.CalendarConfig aCT_RetriveCalendarConfig(IContext context)
	{
		Object result = aCT_RetriveCalendarConfigBuilder().execute(context);
		return result == null ? null : gestaoturbo.proxies.CalendarConfig.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder budgetItem_TotalPrice_CalculationBuilder(
		gestaoturbo.proxies.BudgetItem _budgetItem
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.BudgetItem_TotalPrice_Calculation");
		builder = builder.withParam("BudgetItem", _budgetItem);
		return builder;
	}

	public static boolean budgetItem_TotalPrice_Calculation(
		IContext context,
		gestaoturbo.proxies.BudgetItem _budgetItem
	)
	{
		Object result = budgetItem_TotalPrice_CalculationBuilder(
				_budgetItem
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tESTE_TechnicalEvaluationBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GestaoTurbo.TESTE_TechnicalEvaluation");
		return builder;
	}

	public static gestaoturbo.proxies.TechnicalEvaluation tESTE_TechnicalEvaluation(IContext context)
	{
		Object result = tESTE_TechnicalEvaluationBuilder().execute(context);
		return result == null ? null : gestaoturbo.proxies.TechnicalEvaluation.initialize(context, (IMendixObject) result);
	}
}
